#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#And compile!
before_script:
  - SMFILE="sourcemod-1.7.0-linux.tar.gz"
  - wget http://www.gsptalk.com/mirror/sourcemod/$SMFILE -O game_upload/$SMFILE
  - cd game_upload
  - tar -xzf $SMFILE
  - cd addons/sourcemod/scripting/
  - wget https://github.com/KyleSanderson/SteamWorks/raw/master/Pawn/includes/SteamWorks.inc -O include/SteamWorks.inc
  - chmod +x spcomp

script: 
  - ./compile.sh sourcebans.sp sourcecomms.sp sbchecker.sp
