language: c

env:
  - VERSION=1.6
  - VERSION=1.7
  - VERSION=1.8

matrix:
  fast_finish: true
  allow_failures:
    - env: VERSION=1.7
    - env: VERSION=1.8

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/$VERSION/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - wget $SMPACKAGE
    - tar -xzf sourcemod-1.6.3-linux.tar.gz
    - cp game_upload/addons/sourcemod/scripting/sourcebans.sp addons/sourcemod/scripting/
    - cp game_upload/addons/sourcemod/scripting/sourcecomms.sp addons/sourcemod/scripting/
    - cp game_upload/addons/sourcemod/scripting/sbchecker.sp addons/sourcemod/scripting/
    - cp game_upload/addons/sourcemod/scripting/include/sourcebans.inc addons/sourcemod/scripting/include/
    - cp game_upload/addons/sourcemod/scripting/include/sourcecomms.inc addons/sourcemod/scripting/include/
    - cp game_upload/addons/sourcemod/scripting/include/SteamWorks.inc addons/sourcemod/scripting/include/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh sourcebans.sp
    - ./compile.sh sourcecomms.sp
    - ./compile.sh sbchecker.sp

after_script:
    - ls compiled/
