#Use the new container-based infrastructure
sudo: false

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6

#Set the build environment
env:
  - VERSION=1.7.0

#And compile!
before_script:
  - SMFILE="sourcemod-$VERSION-linux.tar.gz"
  - wget "http://www.gsptalk.com/mirror/sourcemod/$SMFILE" -O game_upload/
  - cd game_upload
  - tar -xzf $SMFILE
  - cd addons/sourcemod/scripting/
  - chmod +x spcomp

script: 
  - ./spcomp sourcebans.sp sourcecomms.sp sbchecker.sp
